import Image from 'next/image'
import Head from 'next/head'
import profilePic from '../../public/images/developer-pic-1.png'
import AnimatedText from '../components/AnimatedText'
import Link from 'next/link'
import { LinkArrow } from '../components/Icons'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-auto">
        <section className='w-full h-full inline-block z-0 bg-light p-32 pt-0'>
          <section className='flex items-center justify-between w-full'>
            <article className='w-1/2'>
              <Image priority src={profilePic} alt='munazar' className='  w-[95%]  h-auto ' />
            </article>
            <article className='w-1/2 flex flex-col items-center self-center'>
              <h1 >
                <AnimatedText className='!text-[3.80rem] !text-left' text='Turning Vision Into Reality With Code.' />
              </h1>
              <p className='my-4 text-base font-medium'>As a skilled full-stack developer, I am dedicated to turning ideas into innovative web applications.
                Explore my latest projects and articles, showcasing my expertise in React.js and web development.
              </p>
              <div className='flex items-center self-start mt-2'>
                <Link href='/dummy.pdf' target={'_blank'} className='flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark  '
                  download={true}
                >Resume  <LinkArrow className={'w-6 ml-1'} />
                </Link>
                <Link
                  className='ml-4 text-lg font-medium capitalize text-dark underline '
                  href='mailto:munazar.ali.001@gmail.com' >Contact</Link>
              </div>
            </article>
          </section>
        </section>

      </main>
    </>
  )
}
